name: Calculate Total LOC Across All Repos

on:
  schedule:
    - cron: "*/30 * * * *"   # 30 dakikada bir (10 dk önerilmez)
  workflow_dispatch:

jobs:
  loc:
    runs-on: ubuntu-latest

    steps:
      - name: Araçları kur
        run: |
          sudo apt-get update
          sudo apt-get install cloc jq -y

      - name: Repoları listele
        env:
          GH_TOKEN: ${{ secrets.LOC_TOKEN }}
        run: |
          page=1
          > repos.txt

          while :; do
            response=$(curl -s -H "Authorization: token $GH_TOKEN" \
              "https://api.github.com/users/Mr-Alperen/repos?per_page=100&page=$page")

            count=$(echo "$response" | jq length)
            [ "$count" -eq 0 ] && break

            echo "$response" | jq -r '.[] | select(.fork == false) | .clone_url' >> repos.txt
            page=$((page+1))
          done

      - name: Tüm repoları klonla ve say
        run: |
          TOTAL=0

          while read repo; do
            echo "Cloning $repo"
            git clone --depth 1 "$repo" temp_repo || continue

            COUNT=$(cloc temp_repo --json --quiet \
              --exclude-dir=.git,node_modules,dist,build,vendor \
              | jq '.SUM.code')

            COUNT=${COUNT:-0}
            echo "Repo LOC: $COUNT"
            TOTAL=$((TOTAL + COUNT))

            rm -rf temp_repo
          done < repos.txt

          echo "TOTAL LOC: $TOTAL"

          cat <<EOF > loc-badge.json
          {
            "schemaVersion": 1,
            "label": "Total Lines of Code",
            "message": "$(numfmt --to=si $TOTAL)+",
            "color": "blue"
          }
          EOF

      - name: Commit badge
        env:
          GH_TOKEN: ${{ secrets.LOC_TOKEN }}
        run: |
          git clone https://x-access-token:${GH_TOKEN}@github.com/Mr-Alperen/Mr-Alperen.git profile
          cd profile

          mv ../loc-badge.json .

          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add loc-badge.json
          git commit -m "Update total LOC badge" || echo "No changes"
          git push
